use assert.reject to test async functions that throw Errors

use assert.throws to test sync function that throws Errors
